#!/bin/bash

HOST=$1
IFACE="wlp2s0"

ip="`ip -4 addr show ${IFACE} | grep -oP '(?<=inet\s)\d+(\.\d+){3}'`"

echo "set ROS_IP to ${ip}"
unset ROS_HOSTNAME
export ROS_IP=$ip

uri="http://${HOST}:11311/"
echo "set ROS_MASTER_URI to $uri"
export ROS_MASTER_URI=$uri
